# ESLint Configuration for Eerie Escapes

root: true

env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - next/core-web-vitals
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'
  - react
  - react-hooks

rules:
  # TypeScript
  '@typescript-eslint/no-unused-vars': 
    - error
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/explicit-module-boundary-types': off
  
  # React
  'react/react-in-jsx-scope': off
  'react/prop-types': off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': warn
  
  # General
  'no-console': 
    - warn
    - allow: ['warn', 'error']
  'prefer-const': error
  'no-var': error

settings:
  react:
    version: detect